apiVersion: apps/v1
kind: Deployment
metadata:
  name: countrycode
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: countrycode
          image: mrityunjaybiswas/countrycode:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # Change to NodePort, ClusterIP, or LoadBalancer as needed

